training:
  epochs: 100
  batch_size: 8
  learning_rate: 0.0001
  weight_decay: 0.0005
  affine_weight_path: 'experiments/affine_train'
  input_size: 512
  base_channels: 8 # 网络宽度。值越大，网络规模越大。
  dataset_path: 'data/processed'
  mean: 0.293794
  std: 0.201630
  jl_thresh_mode: "percentile_80" # 可选策略：percentile_80, mean_plus_std, median_plus_mad
  patience: 20
  min_delta: 0.001